<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/Miscellaneous\factbook.xml_PRECOMPRESSION.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/Miscellaneous\factbook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\Miscellaneous\factbook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/Miscellaneous\factbook.xml_STRICT.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/Miscellaneous\factbook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\Miscellaneous\factbook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/Miscellaneous\factbook.xml_STRICT_BYTEALIGNED.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/Miscellaneous\factbook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\Miscellaneous\factbook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml_DEFAULT.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\notebook\notebook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml_DEFAULT_BYTEALIGNED.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\notebook\notebook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml_NOSCHEMA.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml</xml>
  <schema/>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml_NOSCHEMA_BYTEALIGN.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml</xml>
  <schema/>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml_PRECOMPRESSION.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\notebook\notebook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml_STRICT.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\notebook\notebook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml_STRICT_BYTEALIGNED.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\notebook\notebook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>
<check-exi>
  <file>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml_STRICT_COMPRESSED.exi</file>
  <xml>test_exi/Queries/converters/exi/movesinstitute.org/notebook\notebook.xml</xml>
  <schema>test_exi\Queries\converters\exi\movesinstitute.org\notebook\notebook.xsd</schema>
  <encoding>ok</encoding>
  <decoding>ok</decoding>
</check-exi>